import 'dart:ui';

import 'package:flutter/material.dart';

class App {
  static const String appName = "OLLAPRO";
  static const String font = "Roboto";
  static const String partnerLogin = "Partner Login";
  static const String credentials = "Enter your credentials to continue";
  static const String mobileNumber = "Mobile Number";
  static const String altMobileNumber = "Alternate Mobile Number";
  static const String loginButton = "LOGIN";
  static const String password = "Password";
  static const String rememberMe = "Remember Me";
  static const String forgotPassword = "Forgot Password?";
  static const String loginToRegisterButton = "OPS.. I DON'T HAVE AN ACCOUNT YET";
  static const String createYourAccount = "Create your Account";
  static const String enterYourDetails = "Enter your details";
  static const String fullName = "Full Name";
  static const String emailAddress = "Email Address";
  static const String confirmPassword = "Confirm Password";
  static const String registerButton = "REGISTER";
  static const String verificationCodeText = "Verification Code";
  static const String verifyText = "Please enter the 6 digits verification code";
  static const String verifyButton = "VERIFY";
  static const String codeText = "Didn't receive the code";
  static const String resendCodeButton = "RESEND CODE";
  static const String forgotText = "Forgot Password";
  static const String mobileText = "Please enter your mobile number";
  static const String submitButton = "SUBMIT";
  static const String completeYourKyc = "Complete Your KYC";
  static const String skip = "Skip";
  static const String personalDetail = "PERSONAL DETAILS";
  static const String title = "Title";
  static const String fName = "First Name";
  static const String lName = "Last Name";
  static const String mName = "Middle Name";
  static const String dob = "Date of Birth";
  static const String gender = "Gender";
  static const String language = "Language Known";
  static const String fatherName = "Father's Name";
  static const String nextButton = "NEXT";
  static const String backButton = "BACK";
  static const String contactDetail = "CONTACT DETAILS";
  static const String communicationAddress = "Communication Address";
  static const String exactPlace = "Exact Place";
  static const String pinCode = "Pin Code";
  static const String state = "State";
  static const String city = "City";
  static const String place = "Place";
  static const String aadhar = "Aadhar Number";
  static const String pan = "PAN Number";
  static const String gst = "GSTIN";
  static const String identifyDetail = "IDENTIFY DETAILS";
  static const String bankDetail = "BANK DETAILS";
  static const String referenceDetail = "REFERENCE";
  static const String reference1 = "References 1";
  static const String reference2 = "References 2";
  static const String bankName = "Bank Name";
  static const String accountNumber = "Account Number";
  static const String account1Number = "Re-type Account Number";
  static const String nameOfHolder = "Name of Account Holder";
  static const String accountType = "Account Type";
  static const String ifscCode = "IFSC Code";
  static const String uploadDocument = "UPLOAD DOCUMENTS";
  static const String name = "Name";
  static const String photo1 = "Photo 1";
  static const String photo2 = "Photo 2";
  static const String chooseFile = "Choose File";
  static const String aadharFront = "Aadhar Front";
  static const String aadharback = "Aadhar Back";
  static const String panCard = "PAN Card";
  static const String cancelledCheque = "Cancelled Cheque";
  static const String selfAttested = "Self Attested Declaration";
  static const String dashBoardTitle = "My DashBoard";
  static const String property = "Property";
  static const String landlord = "Landlord";
  static const String tenant = "Tenant";
  static const String rewardBasket = "Reward Basket";
  static const String seeAll = "See All";
  static const String newListProperty = "New List Properties";
  static const String nonVerifiedTenantText = "Non Verified Tenant";
  static const String addNewLandLord = "ADD NEW LANDLORD";
  static const String addNewLandLordText = "Add New LandLord";




  //images
  static const String splashBg = "assets/splashbg.png";
  static const String splashLogo = "assets/splashlogo.png";
  static const String loginBg = "assets/loginBg.png";
  static const String visibility = "assets/view.png";
  static const String backButtonLogo = "assets/back@2x.png";
  static const String passwordLogo = "assets/password.png";
  static const String checkedButtonLogo = "assets/checked.png";
  static const String mobileLogo = "assets/mobile.png";
  static const String unCheckedButtonLogo = "assets/uncheck.png";
  static const String emailLogo = "assets/email.png";
  static const String personLogo = "assets/user.png";
  static const String calendarLogo = "assets/calendar.png";
  static const String dashBoardBg = "assets/main-bg@3x.png";
  static const String bannerDashLogo = "assets/banner@3x.png";
  static const String landLordDashLogo = "assets/landlord@2x.png";
  static const String leftArrowLogo = "assets/left-arrow.png";
  static const String menuDrawerLogo = "assets/menu.png";
  static const String notificationLogo = "assets/notification@2x.png";
  static const String tenantUSer = "assets/nv-tenant@2x.png";
  static const String propertyLogo = "assets/property@2x.png";
  static const String property1Logo = "assets/property-1@3x.png";
  static const String rewardBasketLogo = "assets/reward-basket@2x.png";
  static const String shareLogo = "assets/share@2x.png";
  static const String tenantLogo = "assets/tenant@2x.png";
  static const String userImage = "assets/user@2x.png";
  static const String delete = "assets/delete@2x.png";
  static const String arrowBack = "assets/arrow.png";
  static const String report = "assets/report@2x.png";
  static const String sideMenu = "assets/sidemenu@2x.png";
  static const String addButton = "assets/add@2x.png";
}

//Colors
final Color primaryColor = Color(0xFF000000);
final Color secondaryColor = Color(0xFF868d92);
final Color yellow = Color(0xFFe59607);
final Color white = Color(0xFFf3f3f3);
final Color red = Colors.red;
final Color grey = Colors.grey.shade300;
final Color grey1 = Colors.grey.shade400;
final Color green = Colors.green;
